### ISSUE TITLE
Spring data jpa and lombok

### ISSUE THREAD

**Issue by kdbrian** [learning-zone/spring-boot-basics#7]
### can we do a directory on spring data jpa and a separate one on Lombok

- Spring data (Java Persistence Api) jpa is a framework used to interact with data sources from spring boot application context

- lombok is a java package that leverages the trouble of creating getters, setters and all the related class methods including the tostring, hashcode and equals. It reduces the amount of boiler plate code to be written

**Comment by learning-zone** [comment]
Please add this section
